ALTER TABLE CUSTOMER DROP CONSTRAINT CNTCTNFRMTNCSTMRCN
ALTER TABLE CUSTOMER DROP CONSTRAINT CSTMNDSTRYDNDSTRYD
ALTER TABLE CUSTOMER DROP CONSTRAINT CSTMRPRNTRDPRNTRID
ALTER TABLE CUSTOMER DROP CONSTRAINT CSTMERSTFFDSTAFFID
ALTER TABLE STAFF_CUSTOMER DROP CONSTRAINT STFFCSTcstmrCSTMRD
ALTER TABLE STAFF_CUSTOMER DROP CONSTRAINT STFFCSTMRStffSTFFD
DROP TABLE CUSTOMER
DROP TABLE CUSTOMERCONTACTINFORMATION
DROP TABLE STAFF
DROP TABLE INDUSTRY
DROP TABLE PRINTER
DROP TABLE Users
DROP TABLE Groups
DROP TABLE STAFF_CUSTOMER
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
