INSERT INTO ADMIN.CUSTOMER (CUSTOMERID,STAFFID_STAFFID,PRINTER_ID_PRINTERID,INDUSTRYID_INDUSTRYID,CUSTOMERFIRSTNAME,CUSTOMERLASTNAME,DATEOFPURCHASE,CONTACTINFORMATION_CUSTOMERCONTACTID)
VALUES (1,2,4,5,'sampreeth','amith','2016-07-15',1);
INSERT INTO ADMIN.CUSTOMER (CUSTOMERID,STAFFID_STAFFID,PRINTER_ID_PRINTERID,INDUSTRYID_INDUSTRYID,CUSTOMERFIRSTNAME,CUSTOMERLASTNAME,DATEOFPURCHASE,CONTACTINFORMATION_CUSTOMERCONTACTID)
VALUES (2,2,3,2,'Nikhil','Vellur','2018-03-10',2);
INSERT INTO ADMIN.CUSTOMER (CUSTOMERID,STAFFID_STAFFID,PRINTER_ID_PRINTERID,INDUSTRYID_INDUSTRYID,CUSTOMERFIRSTNAME,CUSTOMERLASTNAME,DATEOFPURCHASE,CONTACTINFORMATION_CUSTOMERCONTACTID)
VALUES (3,1,1,8,'ujwal','kumar','2018-10-11',3);
INSERT INTO ADMIN.CUSTOMER (CUSTOMERID,STAFFID_STAFFID,PRINTER_ID_PRINTERID,INDUSTRYID_INDUSTRYID,CUSTOMERFIRSTNAME,CUSTOMERLASTNAME,DATEOFPURCHASE,CONTACTINFORMATION_CUSTOMERCONTACTID)
VALUES (4,1,2,7,'vishal','shankar','2013-12-22',4);